version: "3"

services:
  server:
    image: node:18.6
    working_dir: /lan
    command: ["sh", "-c", "yarn install && yarn dev"]
    container_name: lan-server
    restart: unless-stopped
    ports:
      - 3000:3000
      - 24678:24678 # HMR Port
    environment:
      HOST: "0.0.0.0"
    env_file:
      - .env
      - .env.local
    depends_on:
      - database
      - mailcatcher
    volumes:
      - ./:/lan
  database:
    container_name: lan-database
    image: "postgres:latest"
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - ./dockerdata/postgres:/data/postgres
    environment:
      PGDATA: "/data/postgres"
    env_file:
      - .env
      - .env.local
  mailcatcher:
    container_name: lan-mailcatcher
    image: schickling/mailcatcher
    restart: unless-stopped
    ports:
      - 8081:1080
      - 1025:1025
    env_file:
      - .env
      - .env.local
  adminer:
    container_name: lan-adminer
    image: adminer
    restart: unless-stopped
    depends_on:
      - database
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: database
    env_file:
      - .env
      - .env.local
