version: "3"

services:
  database:
    container_name: lan-database
    image: "postgres:latest"
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - ./dockerdata/postgres:/data/postgres
    environment:
      PGDATA: "/data/postgres"
    env_file:
      - .env
      - .env.local
  mailcatcher:
    container_name: lan-mailcatcher
    image: schickling/mailcatcher
    restart: unless-stopped
    ports:
      - 8081:1080
      - 1025:1025
    env_file:
      - .env
      - .env.local
  adminer:
    container_name: lan-adminer
    image: adminer
    restart: unless-stopped
    depends_on:
      - database
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: database
    env_file:
      - .env
      - .env.local
