version: "3"

services:
  nuxt:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nuxt-server
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - .:/lan
