# This Dockerfile requires you to mount the root of the repository to /lan!
FROM node:18.6
WORKDIR /lan

# Set env variables required.
ENV HOST 0.0.0.0
ENV CHOKIDAR_USEPOLLING=true

# Start the application in dev mode.
EXPOSE 3000
CMD yarn install && yarn dev
