name: Linting
on:
  - pull_request
  - push

jobs:
  build:
    name: Smoke test building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: yarn install
      - run: yarn build
  typecheck:
    name: Typecheck TypeScript code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: yarn install
      - run: yarn typecheck
  superlinter:
    name: Run superlinter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          YAML_ERROR_ON_WARNING: true
  prettier:
    name: Validate Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          persist-credentials: false
      - uses: creyD/prettier_action@v4.2
        with:
          dry: True
          prettier_options: "--check ."
          github_token: ${{ secrets.GITHUB_TOKEN }}
